name: hearu
description: "Ruang aman untuk berbagi cerita dan mendengarkan sesama."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^2.4.9

  supabase_flutter: ^2.10.3

  google_sign_in: ^6.1.6

  google_fonts: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
